import "./globals.css";
import { Fira_Code } from "next/font/google";

// Load the font
const firaCode = Fira_Code({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-fira-code", // optional: enables CSS variable usage
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={firaCode.className}>
			<body>{children}</body>
		</html>
	);
}
